#GET VERSION
GET http://localhost:3000 HTTP/1.1

###

#CRIA USUARIO
POST http://localhost:3000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Guilherme Karam",
  "email": "guilherme.klm22@gmail.com",
  "password": "senha123"
}

###

#LOGIN USUARIO
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "guilherme.klm22@gmail.com",
  "password": "senha123"
}

###

#CRIA SALA
POST http://localhost:3000/api/v1/rooms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwNGQxYTVlY2ZmNzQ4ZTBjOWVkZmEiLCJpYXQiOjE3MjcwMjYyNjMsImV4cCI6MTcyNzAyODA2M30.u0FtyiHtK8M2Pp8ScK7seOvgWKI6xgSWKLdrE-L-QRo

{
  "name": "Sala A",
  "type": "MEETING_ROOM",
  "numberOfSeats": 20,
  "location": {
    "address": "R. Cel. Genuíno, 130 - Centro Histórico, Porto Alegre - RS",
    "floor": 1,
    "roomLabel": "A"
  }
}

###

#Busca lista de salas
GET http://localhost:3000/api/v1/rooms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwNGQxYTVlY2ZmNzQ4ZTBjOWVkZmEiLCJpYXQiOjE3MjgwODg3MDMsImV4cCI6MTcyODA5MDUwM30.8mjLiyzUrZeuGSztx1X3ERiVDB-tQFWSmwIy3-PVWog