enum TypeErr {
  BUSINESS_ERROR,
  VALIDATION_ERROR,
  AUTHENTICATION_ERROR,
  DATABASE_CONNECTION_ERROR,
  NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
  RECORD_NOT_FOUND_ERROR,
  AUTHORIZATION_ERROR
}
